// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.pay.domain;

import org.esupportail.pay.domain.ScienceConfReference;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ScienceConfReference_Roo_Configurable {
    
    declare @type: ScienceConfReference: @Configurable;
    
}
